apiVersion: apps/v1
kind: Deployment
metadata:
  name: hero-manager-marvel
  labels:
    name: hero-manager-marvel
spec:
  selector:
    matchLabels:
      name: hero-manager-marvel
  replicas: 1
  template:
    metadata:
      labels:
        name: hero-manager-marvel
    spec:
      containers:
        - name: hero-manager-marvel
          image: docker.io/library/hero_manager_marvel_image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          resources: {}
          env:
            - name: PORT
              value: "8082"
            - name: MARVEL_PUBLIC_KEY
              value: '598d68bc275936dfe34163748941f721'
            - name: MARVEL_PRIVATE_KEY
              value: '2115637f794d98e8bb05a0f6e6be19ec6c12082d'

